=== DavidMyrseth/ToDo-xml-project/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tasks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="task" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="dim1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="date" type="xs:date"/>
                                        <xs:element name="deadline" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="dim2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="dim3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="info" type="xs:string"/>
                                        <xs:element name="comment" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== DavidMyrseth/ToDo-xml-project/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="schema.xsd">

    <task id="1">
        <dim1>
            <date>2025-05-10</date>
            <deadline>2025-05-15</deadline>
        </dim1>
        <dim2>
            <subject>Matemaatika</subject>
            <type>Kodutöö</type>
        </dim2>
        <dim3>
            <info>Kontrolltöö teema 7</info>
            <comment>Vaja lõpetada enne reedet</comment>
        </dim3>
    </task>

    <task id="2">
        <dim1>
            <date>2025-06-01</date>
            <deadline>2025-06-10</deadline>
        </dim1>
        <dim2>
            <subject>Füüsika</subject>
            <type>Test</type>
        </dim2>
        <dim3>
            <info>Kordamisküsimused</info>
            <comment>Oluline eksamiks</comment>
        </dim3>
    </task>

    <task id="3">
        <dim1>
            <date>2025-05-20</date>
            <deadline>2025-05-25</deadline>
        </dim1>
        <dim2>
            <subject>Inglise keel</subject>
            <type>Essee</type>
        </dim2>
        <dim3>
            <info>Esitada PDF kujul</info>
            <comment>Minimaalne pikkus 600 sõna</comment>
        </dim3>
    </task>

</tasks>
